### ISSUE TITLE
app without mstpd

### ISSUE THREAD

**Issue by finasfinas** [tano-systems/luci-app-mstpd#1]
can I use this app to simply look at the state of a br-lan bridge configured with stp using the built in openwrt bridge configuration?
Also is this usable on current trunk?
And finally, there is a ustp package made by one of the openwrt developers. Is this also usable with it?

cheers

**Comment by namedun** [comment]
No, this app requires mstpd to work. You cannot view the status of a bridge without mstpd with this application. 

It will most likely not work with the current trunk. Moreover, this application is developed not for OpenWrt, but for our own [TanoWrt](https://github.com/tano-systems/meta-tanowrt) distribution, which is based on OpenWrt. So it is not guaranteed to work in OpenWrt at all.

This application was developed long before ustp appeared in OpenWrt. But support for ustp is planned.

**Comment by finasfinas** [comment]
cool, thanks for replying in such detail.

- Can you tell me what is the goal of TanoWRT? I tried to find information and couldn't find an answer on the git repo or website ( Russian? )
- I understand that you goal is working towards Tano but would you be considering adding at least simple/partial support for bridge status into OpenWRT luci?

**Comment by namedun** [comment]
Yes, our site is in Russian. I'm sorry, we still can't get enough time to translate and publish the English version. Also it's in our plans.

We primarily focus on embedded devices for industrial applications using Linux kernel with real-time patch. In addition, our distribution has a firmware upgrade system with the ability to centralized firmware upgrade on any number of devices and the possibility of automatic rollback in case of failed firmware, which is very important in industrial applications. All of this is not present in the original OpenWrt and most likely never will be. We collaborate with some manufacturers of industrial PLC and switches which use TanoWrt as a base system and later on embed their own functionality there over our base system. 

Besides this, TanoWrt is an attempt to integrate some OpenWrt developments (such as LuCI web UI) into the infrastructure of the OpenEmbedded build system. Most of the SoC manufacturers provide ready to use well supported BSP layers for their microprocessors, that can be easily used for TanoWrt integration on the new hardware. In particular, due to the OpenEmbedded layers we provide support of Russian microprocessors in TanoWrt, such as [Baikal Electronics](https://www.baikalelectronics.com/products/338/) or [Elvees](https://elvees.ru/en).

I think we will consider the possibility of displaying the bridge state within this application when we perform integration of ustp support.

**Comment by finasfinas** [comment]
Again, many thanks for you time. 
Best wishes for you and your project.
